server:
  port: 9090
  servlet:
    context-path: /api
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/stockerdb?serverTimezone=CET
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: parasnorik@gmail.com
    password: pls ne lopd el
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
